package passivetorch.references;

import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

public class Meta
{
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = "Passive Torch prevents the spawning of mobs in the local area";
        metadata.url = "";
        metadata.version = Reference.VERSION_FULL;
        metadata.authorList = Arrays.asList("hilburn");
        metadata.credits = "";
        metadata.autogenerated = false;
        return metadata;
    }
}
